### ISSUE TITLE
Young project, but looks promising!

### ISSUE THREAD

**Issue by pthom** [KaiSzuttor/cpp_project_template#1]
I stumbled upon your project by searching for "pitchfork cpp template" in github. 
Your choices (doctest, pitchfork & github actions) make sense.

Anyway, that was just meant as an encouragement, you may close this issue.

**Comment by KaiSzuttor** [comment]
thanks

**Comment by KaiSzuttor** [comment]
BTW: I'm open to suggestions what could be added @pthom, *e.g.* I want to add coverage builds

**Comment by pthom** [comment]
Ok, let me give you the suggestions I thought of. 

* .gitignore: 
mention in the doc that http://gitignore.io can give a good starting point
May be add an example gitignore file, for example http://www.gitignore.io/api/c++,linux,clion,qtcreator,visualstudio,visualstudiocode,xcode

* [EditorConfig](https://editorconfig.org/): add a .editorconfig file ?
EditorConfig is a good initiative, although not pervasive accross text editors

* Add a .clang-format file?
May be add an example .clang-format file, and mention that https://www.clangformat.com/ can help customize it. clang-format should become part of the standard tooling IMHO.

* clang tidy: 
May be mention that clang-tidy can be a valuable tool, and that a ".clang-tidy" can be interesting for static analysis. May be include an example. 

* Test: Introduce a separate main_test library `src/main_test/CMakeLists.txt`
 that could be linked by all test targets regardless of their location.

PS: Those are all only suggestions ;-)

**Comment by KaiSzuttor** [comment]
thanks for your suggestions, I already incorporated some of your ideas! I've never used ```EditorConfig```, have to look into this.
